name: Render Mermaid Diagrams

on:
  push:
    branches:
      - main  # Or any other branch you want to trigger the action on

jobs:
  render-mermaid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}