name: Render Mermaid Diagrams

on:
  push:
    branches:
      - main 

jobs:
  render-mermaid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Update to latest version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use 'token' instead of 'github-token'

      - name: Find and Render Mermaid Diagrams
        uses: vsoch/mmdc@v1.0.0
        with:
          files: 'README.md' 

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git   
 add .
          git commit   
 -m "Render Mermaid diagrams"
          git push 